namespace:
  name: demo
  tier: test

image:
  repository: nginx
  tag: alpine
  policy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: "50m"
    memory: "256Mi"

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"
